blank_issues_enabled: true
contact_links:
    - name: Q & A
      url: https://github.com/bb1/vscode-gitlens/discussions
      about: Ask and answer questions about Offline GitLense
    - name: Documentation
      url: https://github.com/bb1/vscode-gitlens#readme
      about: Read the project documentation
